--------------------------------------------------------
--  File created - szombat-�prilis-30-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALLASHIRDETO
--------------------------------------------------------

  CREATE TABLE "IVANOV"."ALLASHIRDETO" 
   (	"ID" NUMBER(10,0), 
	"TITULUS" VARCHAR2(10 BYTE), 
	"VEZETEKNEV" VARCHAR2(50 BYTE), 
	"KERESZTNEV" VARCHAR2(50 BYTE), 
	"FENYKEP_UT" VARCHAR2(200 BYTE), 
	"TELEFONSZAM" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ALLASKERESO
--------------------------------------------------------

  CREATE TABLE "IVANOV"."ALLASKERESO" 
   (	"ID" NUMBER(10,0), 
	"TITULUS" VARCHAR2(10 BYTE), 
	"VEZETEKNEV" VARCHAR2(50 BYTE), 
	"KERESZTNEV" VARCHAR2(50 BYTE), 
	"FENYKEP_UT" VARCHAR2(200 BYTE), 
	"SZULIDO" DATE, 
	"LAKCIM" VARCHAR2(50 BYTE), 
	"TARTHELY" VARCHAR2(50 BYTE), 
	"RADIUS" NUMBER(4,0), 
	"ONELETRAJZ_ID" NUMBER(10,0), 
	"ROVID_LEIRAS" VARCHAR2(100 BYTE), 
	"EGYEB_INFO" VARCHAR2(100 BYTE), 
	"TELEFONSZAM" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CEG
--------------------------------------------------------

  CREATE TABLE "IVANOV"."CEG" 
   (	"ID" NUMBER(10,0), 
	"NEV" VARCHAR2(50 BYTE), 
	"FENYKEP_UT" VARCHAR2(200 BYTE), 
	"ROVID_LEIRAS" VARCHAR2(250 BYTE), 
	"TELEFONSZAM" VARCHAR2(10 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FELHASZNALO
--------------------------------------------------------

  CREATE TABLE "IVANOV"."FELHASZNALO" 
   (	"ID" NUMBER(10,0), 
	"FELHASZNALONEV" VARCHAR2(20 BYTE), 
	"JELSZO" VARCHAR2(50 BYTE), 
	"STATUS" NUMBER(1,0), 
	"IS_ADMIN" NUMBER(1,0), 
	"ALLASKERESO_ID" NUMBER(10,0), 
	"ALLASHIRDETO_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ONELETRAJZ
--------------------------------------------------------

  CREATE TABLE "IVANOV"."ONELETRAJZ" 
   (	"ID" NUMBER(10,0), 
	"VEGZETTSEG_ID" VARCHAR2(200 BYTE), 
	"TAPASZTALAT_ID" VARCHAR2(200 BYTE), 
	"SOFTSKILL_ID" VARCHAR2(200 BYTE), 
	"REFERENCIA_ID" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SOFTSKILL
--------------------------------------------------------

  CREATE TABLE "IVANOV"."SOFTSKILL" 
   (	"ID" NUMBER(10,0), 
	"NEV" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAPASZTALAT
--------------------------------------------------------

  CREATE TABLE "IVANOV"."TAPASZTALAT" 
   (	"ID" NUMBER(10,0), 
	"HELY" VARCHAR2(200 BYTE), 
	"IDO_KEZDET" DATE, 
	"IDO_VEG" DATE, 
	"LEIRAS" VARCHAR2(600 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "IVANOV"."TEST" 
   (	"ID" NUMBER(3,0), 
	"FELHASZNALONEV" VARCHAR2(50 BYTE), 
	"JELSZO" VARCHAR2(50 BYTE), 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VEGZETTSEG
--------------------------------------------------------

  CREATE TABLE "IVANOV"."VEGZETTSEG" 
   (	"ID" NUMBER(10,0), 
	"HELY" VARCHAR2(200 BYTE), 
	"IDO_KEZDET" DATE, 
	"IDO_VEG" DATE, 
	"LEIRAS" VARCHAR2(600 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into IVANOV.ALLASHIRDETO
SET DEFINE OFF;
REM INSERTING into IVANOV.ALLASKERESO
SET DEFINE OFF;
Insert into IVANOV.ALLASKERESO (ID,TITULUS,VEZETEKNEV,KERESZTNEV,FENYKEP_UT,SZULIDO,LAKCIM,TARTHELY,RADIUS,ONELETRAJZ_ID,ROVID_LEIRAS,EGYEB_INFO,TELEFONSZAM,EMAIL) values ('1','dr.','Kiss','Konr�d',null,to_date('90-�PR.  -01','RR-MON-DD'),'5440 Kunszentm�rton, Kossuth u. 1.',null,'20','1','Gy�gyszer�szeti k�mikus �s egy�b labor�ns munkak�r�k ir�nt �rdekl�dik.',null,'06301234567','felh@fel.hu');
REM INSERTING into IVANOV.CEG
SET DEFINE OFF;
REM INSERTING into IVANOV.FELHASZNALO
SET DEFINE OFF;
Insert into IVANOV.FELHASZNALO (ID,FELHASZNALONEV,JELSZO,STATUS,IS_ADMIN,ALLASKERESO_ID,ALLASHIRDETO_ID) values ('1','ivanov','ivanov','1','1',null,null);
Insert into IVANOV.FELHASZNALO (ID,FELHASZNALONEV,JELSZO,STATUS,IS_ADMIN,ALLASKERESO_ID,ALLASHIRDETO_ID) values ('2','admin','admin','1','1',null,null);
Insert into IVANOV.FELHASZNALO (ID,FELHASZNALONEV,JELSZO,STATUS,IS_ADMIN,ALLASKERESO_ID,ALLASHIRDETO_ID) values ('3','felh1','felh1','1','0','1',null);
REM INSERTING into IVANOV.ONELETRAJZ
SET DEFINE OFF;
Insert into IVANOV.ONELETRAJZ (ID,VEGZETTSEG_ID,TAPASZTALAT_ID,SOFTSKILL_ID,REFERENCIA_ID) values ('1','1,2','1,2,3','1,2,3,4',null);
REM INSERTING into IVANOV.SOFTSKILL
SET DEFINE OFF;
Insert into IVANOV.SOFTSKILL (ID,NEV) values ('1','pontos');
Insert into IVANOV.SOFTSKILL (ID,NEV) values ('2','j� vezet�');
Insert into IVANOV.SOFTSKILL (ID,NEV) values ('3','k�nnyen alkalmazkod�');
Insert into IVANOV.SOFTSKILL (ID,NEV) values ('4','hat�rozott');
REM INSERTING into IVANOV.TAPASZTALAT
SET DEFINE OFF;
Insert into IVANOV.TAPASZTALAT (ID,HELY,IDO_KEZDET,IDO_VEG,LEIRAS) values ('1','Szeged, Minta Bt.',to_date('15-M�J.  -22','RR-MON-DD'),to_date('19-DEC.  -31','RR-MON-DD'),'Laborasszisztens');
Insert into IVANOV.TAPASZTALAT (ID,HELY,IDO_KEZDET,IDO_VEG,LEIRAS) values ('2','Szeged, SZTE',to_date('17-�PR.  -30','RR-MON-DD'),null,'K�ls�s gyakorlatvezet�');
Insert into IVANOV.TAPASZTALAT (ID,HELY,IDO_KEZDET,IDO_VEG,LEIRAS) values ('3','Egy�ni v�llalkoz�s',to_date('20-FEBR. -01','RR-MON-DD'),null,'Laboreszk�z�k �s anyagok beszerz�se, elsz�ll�t�sa');
REM INSERTING into IVANOV.TEST
SET DEFINE OFF;
Insert into IVANOV.TEST (ID,FELHASZNALONEV,JELSZO,STATUS) values ('1','Asd','sdsasdsads','1');
REM INSERTING into IVANOV.VEGZETTSEG
SET DEFINE OFF;
Insert into IVANOV.VEGZETTSEG (ID,HELY,IDO_KEZDET,IDO_VEG,LEIRAS) values ('1','SZTE',to_date('09-JAN.  -01','RR-MON-DD'),to_date('14-JAN.  -01','RR-MON-DD'),'Gy�gyszer�szeti k�mikus BSc + MSc k�pz�s (summa cum laude)');
Insert into IVANOV.VEGZETTSEG (ID,HELY,IDO_KEZDET,IDO_VEG,LEIRAS) values ('2','PKE',to_date('14-JAN.  -01','RR-MON-DD'),to_date('16-JAN.  -01','RR-MON-DD'),'Laborbiztons�gi technikusi szakir�ny� tov�bbk�pz�s');
--------------------------------------------------------
--  DDL for Index ALLASKERESO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IVANOV"."ALLASKERESO_PK" ON "IVANOV"."ALLASKERESO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALLASHIRDETO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IVANOV"."ALLASHIRDETO_PK" ON "IVANOV"."ALLASHIRDETO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IVANOV"."TABLE1_PK" ON "IVANOV"."ONELETRAJZ" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TAPASZTALAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IVANOV"."TAPASZTALAT_PK" ON "IVANOV"."TAPASZTALAT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FELHASZNALO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IVANOV"."FELHASZNALO_PK" ON "IVANOV"."FELHASZNALO" ("ID", "FELHASZNALONEV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VEGZETTSEG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IVANOV"."VEGZETTSEG_PK" ON "IVANOV"."VEGZETTSEG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SOFTSKILL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IVANOV"."SOFTSKILL_PK" ON "IVANOV"."SOFTSKILL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CEG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IVANOV"."CEG_PK" ON "IVANOV"."CEG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FELHASZNALO
--------------------------------------------------------

  ALTER TABLE "IVANOV"."FELHASZNALO" ADD CONSTRAINT "FELHASZNALO_PK" PRIMARY KEY ("ID", "FELHASZNALONEV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IVANOV"."FELHASZNALO" MODIFY ("IS_ADMIN" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."FELHASZNALO" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."FELHASZNALO" MODIFY ("JELSZO" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."FELHASZNALO" MODIFY ("FELHASZNALONEV" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."FELHASZNALO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALLASKERESO
--------------------------------------------------------

  ALTER TABLE "IVANOV"."ALLASKERESO" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."ALLASKERESO" MODIFY ("TELEFONSZAM" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."ALLASKERESO" ADD CONSTRAINT "ALLASKERESO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IVANOV"."ALLASKERESO" MODIFY ("RADIUS" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."ALLASKERESO" MODIFY ("SZULIDO" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."ALLASKERESO" MODIFY ("KERESZTNEV" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."ALLASKERESO" MODIFY ("VEZETEKNEV" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."ALLASKERESO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ONELETRAJZ
--------------------------------------------------------

  ALTER TABLE "IVANOV"."ONELETRAJZ" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IVANOV"."ONELETRAJZ" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEG
--------------------------------------------------------

  ALTER TABLE "IVANOV"."CEG" MODIFY ("TELEFONSZAM" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."CEG" ADD CONSTRAINT "CEG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IVANOV"."CEG" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."CEG" MODIFY ("NEV" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."CEG" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALLASHIRDETO
--------------------------------------------------------

  ALTER TABLE "IVANOV"."ALLASHIRDETO" MODIFY ("TELEFONSZAM" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."ALLASHIRDETO" ADD CONSTRAINT "ALLASHIRDETO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IVANOV"."ALLASHIRDETO" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."ALLASHIRDETO" MODIFY ("KERESZTNEV" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."ALLASHIRDETO" MODIFY ("VEZETEKNEV" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."ALLASHIRDETO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VEGZETTSEG
--------------------------------------------------------

  ALTER TABLE "IVANOV"."VEGZETTSEG" ADD CONSTRAINT "VEGZETTSEG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IVANOV"."VEGZETTSEG" MODIFY ("LEIRAS" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."VEGZETTSEG" MODIFY ("IDO_KEZDET" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."VEGZETTSEG" MODIFY ("HELY" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."VEGZETTSEG" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SOFTSKILL
--------------------------------------------------------

  ALTER TABLE "IVANOV"."SOFTSKILL" ADD CONSTRAINT "SOFTSKILL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IVANOV"."SOFTSKILL" MODIFY ("NEV" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."SOFTSKILL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "IVANOV"."TEST" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."TEST" MODIFY ("JELSZO" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."TEST" MODIFY ("FELHASZNALONEV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TAPASZTALAT
--------------------------------------------------------

  ALTER TABLE "IVANOV"."TAPASZTALAT" ADD CONSTRAINT "TAPASZTALAT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IVANOV"."TAPASZTALAT" MODIFY ("LEIRAS" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."TAPASZTALAT" MODIFY ("IDO_KEZDET" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."TAPASZTALAT" MODIFY ("HELY" NOT NULL ENABLE);
  ALTER TABLE "IVANOV"."TAPASZTALAT" MODIFY ("ID" NOT NULL ENABLE);
